belleluxe/belleluxe/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('adm/', include("core.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belleluxe/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views


app_name="core"
urlpatterns=[
    path('', views.adm.as_view(), name="adm"),

    path('camping/', views.Campaign.as_view(), name="campaign"),
    path('detail/camping/<int:pk>/', views.DetailCampaign.as_view(), name='detail_campaign'),
    path('update/camping/<int:pk>/', views.UpdateCampaign.as_view(), name='update_campaign'),
    path('delete/camping/<int:pk>/', views.DeleteCampaign.as_view(), name='delete_campaign'),
    path('new/camping/', views.NewCampaign.as_view(), name='Newcampaign'),

    path('list/gender/', views.list_gender.as_view(), name="gender"),
    path('detail/gender/<int:pk>/', views.DetailGender.as_view(), name='detail_gender'),
    path('update/gender/<int:pk>/', views.UpdateGender.as_view(), name='update_gender'),
    path('delete/gender/<int:pk>/', views.DeleteGender.as_view(), name='delete_gender'),
    path('new/gender/', views.NewGender.as_view(), name='Newgender'),

    path('list/category/', views.list_category.as_view(), name="category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name='update_category'),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('new/category/', views.NewCategory.as_view(), name='Newcategory'),

    path('list/payment/', views.list_payment.as_view(), name="payment"),
    path('detail/payment/<int:pk>/', views.DetailPayment.as_view(), name='detail_payment'),
    path('update/payment/<int:pk>/', views.UpdatePayment.as_view(), name='update_payment'),
    path('delete/payment/<int:pk>/', views.DeletePayment.as_view(), name='delete_payment'),
    path('new/payment/', views.NewPayment.as_view(), name='Newpayment'),

    path('product/', views.Product.as_view(), name="product"),
    path('recover/product/<int:pk>/', views.RecoverProduct.as_view(), name='recover_product'),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name='update_product'),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('new/product/', views.NewProduct.as_view(), name='new_product'),
   
]

belleluxe/home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

# NOOO 😨 eso truena el django 😔
#oh perdon ya no le muevo, perdoname compañero unu. 
#adios
app_name="home"
urlpatterns=[
    path('', views.inicio.as_view(), name="inicio"),
    path('nosotros/', views.nosotros.as_view(), name="nosotros"),
    path('blog/', views.blog.as_view(), name="blog"),
    path('servicios/', views.servicios.as_view(), name="servicios"),
    path('politicas/', views.politicas.as_view(), name="politicas"),
    path('carrito/', views.carrito.as_view(), name="carrito"),
]

belleluxe/templates/base/admin.html
<html>
    <head>
        <meta charset="utf-8">

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .sidebar {
              margin: 0;
              padding: 0;
              width: 170px;
              background-color: #ccd1cb;
              position: fixed;
              height: 100%;
              overflow: auto;
            }
            .sidebar a {
              display: block;
              color: black;
              padding: 16px;
              text-decoration: none;
            }
            
            .sidebar a.active {
              background-color: #748e81;
              color: white;
            }
            .sidebar a:hover:not(.active) {
              background-color: #555;
              color: #ccd1cb;
            }
            div.content {
              margin-left: 200px;
              padding: 1px 16px;
              height: 1000px;
            }
            @media screen and (max-width: 700px) {
              .sidebar {
                width: 100%;
                height: auto;
                position: relative;
              }
              .sidebar a {float: left;}
              div.content {margin-left: 0;}
            }
            @media screen and (max-width: 400px) {
              .sidebar a {
                text-align: center;
                float: none;
              }
            } 
            body{
            background-color : #e9ede8
            }
        </style>
        
    </head> 
    <body>
        <!-- The sidebar -->
<div class="sidebar">
    <a class="active">Belle d'luxe Admin</a>
    <a href="{% url 'core:product'%}">Productos</a>
    <a href="{% url 'core:category' %}">Categorias</a>
    <a href="{% url 'core:campaign' %}">Campañas</a>    
    <a href="{% url 'core:gender' %}">Generos</a>
    <a href="{% url 'core:payment' %}">Metodos de pagos</a>
    <a href="#">Ordenes</a>
    <a href="#">Clientes</a>
    <a href="{% url 'home:inicio' %}">Salir</a>
  </div>
  
  <!-- Page content -->
  <div class="content">
    {% block content %}
    {% endblock content %}
  </div> 
                    
           
    </body>
</html>

belleluxe/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <style>
        body {
            background-color:#434945;
        }
        
    </style>
  

</head>
<body>


    <!-- barra de navegacion  -->
    <nav class="navbar navbar-expand-lg" style="background-color: rgba(0, 0, 0, 0.2);"  data-bs-theme="dark" >
        <div class="container-fluid">
            <a href="{% url 'home:inicio' %}" class = navbar-brand>BELLE D' LUXE</a>    
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
                    <li class="nav-item" ><a class="nav-link active" aria-current="page" href="#">Hombre</a></li>
                    <li class="nav-item" ><a class="nav-link active" aria-current="page" href="#">Mujer</a></li>
                </ul>                
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding-right: 30px;">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
                <form class="container-fluid">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Buscar" aria-label="Buscar" aria-describedby="basic-addon1">
                      <span class="input-group-text" id="basic-addon1"><i class="bi bi-search"></i></span>
                    </div>
                </form>                
             
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person" style="font-size: 150%; color: white;"></i></a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Perfil</a></li>
                        <li><a class="dropdown-item" href="{% url 'core:adm' %}">Admin</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Login</a></li>
                        <li><a class="dropdown-item" href="#">Sign up</a></li>
                        <li><a class="dropdown-item" href="#">Log out</a></li>
                        

                    </ul>
                    <li class="nav-item" ><a class="nav-link active" aria-current="page" href="#">  <i class="bi bi-heart" style="font-size: 140%; color: white;"></i></a></li>
                    <li class="nav-item" ><a class="nav-link active" aria-current="page" href="{% url 'home:carrito' %}">  <i class="bi bi-cart" style="font-size: 150%; color: white;"></i></a></li>
         
                </li>  
            <!--  -->
            </ul> 
        </div>

    </nav>
      {% block content %}

      {% endblock content %}
      <div class="position-absolute top-100 start-50 translate-middle"><p> </p></div>
      <!-- Grid container -->
      <div class="container pt-4 text-center">



        <div class="text-center text-white p-3">
            <ul>
                <a class="text-white" href="{% url 'home:nosotros' %}">Sobre belle d'luxe</a>
                <li class="list-inline-item"></li>
                <li class="list-inline-item"></li>
                <a class="text-white" href="{% url 'home:blog' %}">Nuestro blog</a>
                <li class="list-inline-item"></li>
                <li class="list-inline-item"></li>
                <a class="text-white" href="{% url 'home:servicios' %}">Servicios</a>

              </ul>              
        </div>




        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.facebook.com/belleedeluxe"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-facebook" style="font-size: 100%; color: white;" ></i></a>
    
          <!-- Google -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.google.com/search?q=belle+de+luxe+tijuana&sca_esv=573670241&biw=1920&bih=937&tbm=lcl&ei=tY0sZb_JKd_UkPIP4OuFqAM&ved=0ahUKEwj_98WqsfmBAxVfKkQIHeB1ATUQ4dUDCAk&uact=5&oq=belle+de+luxe+tijuana&gs_lp=Eg1nd3Mtd2l6LWxvY2FsIhViZWxsZSBkZSBsdXhlIHRpanVhbmEyChAhGKABGMMEGApI_hBQkw1Ykw1wAHgAkAEAmAGTAaAB2gKqAQMxLjK4AQPIAQD4AQHCAgUQABiiBMICCBAAGIkFGKIEiAYB&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[32.52364412063617,-116.93859226079246],[32.49498109755391,-117.00296527714988]]"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-google" style="font-size: 100%; color: white;"></i
          ></a>
    
          <!-- Instagram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.instagram.com/belleedeluxe/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-instagram" style="font-size: 100%; color: white;" ></i></a>


            <!-- Tiktok -->
            <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.tiktok.com/@belleedeluxe"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-tiktok" style="font-size: 100%; color: white;" ></i></a>
        </section>
        <!-- Section: Social media -->

        

    </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        <ul class="list-inline">
            <li class="list-inline-item">            @belledeluxe Baja California Norte, México             </li>
            <li class="list-inline-item"></li>
            <a class="text-white" href="{% url 'home:politicas' %}">politica de privacidad y cookies | condiciones de venta</a>
          </ul>              
      </div>
      <!-- Copyright -->
    


      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>    
</body>
</html>

belleluxe/templates/base/principal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <style>
        body {
            background-color:#ffffff;
        }
        
    </style>

</head>
<body>


    <!-- barra de navegacion  -->
    <nav class="navbar navbar-expand-lg" style="background-color: #434945;"  data-bs-theme="dark" >
        <div class="container-fluid">
            <a href="{% url 'home:inicio' %}" class = navbar-brand>BELLE D' LUXE</a>    
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
                </ul>                
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent"  >
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
                <form class="container-fluid">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Buscar" aria-label="Buscar" aria-describedby="basic-addon1">
                      <span class="input-group-text" id="basic-addon1"><i class="bi bi-search"></i></span>
                    </div>
                </form>                

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person" style="font-size: 150%; color: white;"></i></a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Perfil</a></li>
                        <li><a class="dropdown-item" href="{% url 'core:adm' %}">Admin</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="login.html">Login</a></li>
                        <li><a class="dropdown-item" href="signup.html">Sign up</a></li>
                        <li><a class="dropdown-item" href="#">Log out</a></li>

                    </ul>
                </li>  
                <li class="nav-item" ><a class="nav-link active" aria-current="page" href="#">  <i class="bi bi-heart" style="font-size: 140%; color: white;"></i></a></li>
                <li class="nav-item" ><a class="nav-link active" aria-current="page" href="carrito.html">  <i class="bi bi-cart" style="font-size: 150%; color: white;"></i></a></li>
            </ul>
        </div>

    </nav>
      {% block content %}
      {% endblock content %}
      <div class="position-absolute top-100 start-50 translate-middle"><p> </p></div>
      <!-- Grid container -->
      <div class="container pt-4 text-center">



        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.facebook.com/belleedeluxe"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-facebook" style="font-size: 100%; color: white;" ></i></a>
    
          <!-- Google -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.google.com/search?q=belle+de+luxe+tijuana&sca_esv=573670241&biw=1920&bih=937&tbm=lcl&ei=tY0sZb_JKd_UkPIP4OuFqAM&ved=0ahUKEwj_98WqsfmBAxVfKkQIHeB1ATUQ4dUDCAk&uact=5&oq=belle+de+luxe+tijuana&gs_lp=Eg1nd3Mtd2l6LWxvY2FsIhViZWxsZSBkZSBsdXhlIHRpanVhbmEyChAhGKABGMMEGApI_hBQkw1Ykw1wAHgAkAEAmAGTAaAB2gKqAQMxLjK4AQPIAQD4AQHCAgUQABiiBMICCBAAGIkFGKIEiAYB&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[32.52364412063617,-116.93859226079246],[32.49498109755391,-117.00296527714988]]"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-google" style="font-size: 100%; color: white;"></i
          ></a>
    
          <!-- Instagram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.instagram.com/belleedeluxe/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-instagram" style="font-size: 100%; color: white;" ></i></a>


            <!-- Tiktok -->
            <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.tiktok.com/@belleedeluxe"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="bi bi-tiktok" style="font-size: 100%; color: white;" ></i></a>
        </section>
        <!-- Section: Social media -->

        

    </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center text-white p-3" style="background-color: #434945;;">
        <ul class="list-inline">
            <li class="list-inline-item">            @belledeluxe Baja California Norte, México             </li>
            <li class="list-inline-item"></li>

          </ul>              
      </div>
      <!-- Copyright -->
    


      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>    
</body>
</html>