belleluxe/belleluxe/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('adm/', include("core.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belleluxe/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views


app_name="core"
urlpatterns=[
    path('', views.adm.as_view(), name="adm"),

    path('camping/', views.Campaign.as_view(), name="campaign"),
    path('detail/camping/<int:pk>/', views.DetailCampaign.as_view(), name='detail_campaign'),
    path('update/camping/<int:pk>/', views.UpdateCampaign.as_view(), name='update_campaign'),
    path('delete/camping/<int:pk>/', views.DeleteCampaign.as_view(), name='delete_campaign'),
    path('new/camping/', views.NewCampaign.as_view(), name='Newcampaign'),

    path('list/gender/', views.list_gender.as_view(), name="gender"),
    path('detail/gender/<int:pk>/', views.DetailGender.as_view(), name='detail_gender'),
    path('update/gender/<int:pk>/', views.UpdateGender.as_view(), name='update_gender'),
    path('delete/gender/<int:pk>/', views.DeleteGender.as_view(), name='delete_gender'),
    path('new/gender/', views.NewGender.as_view(), name='Newgender'),

    path('list/category/', views.list_category.as_view(), name="category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name='update_category'),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('new/category/', views.NewCategory.as_view(), name='Newcategory'),

    path('list/payment/', views.list_payment.as_view(), name="payment"),
    path('detail/payment/<int:pk>/', views.DetailPayment.as_view(), name='detail_payment'),
    path('update/payment/<int:pk>/', views.UpdatePayment.as_view(), name='update_payment'),
    path('delete/payment/<int:pk>/', views.DeletePayment.as_view(), name='delete_payment'),
    path('new/payment/', views.NewPayment.as_view(), name='Newpayment'),

    path('product/', views.Product.as_view(), name="product"),
    path('recover/product/<int:pk>/', views.RecoverProduct.as_view(), name='recover_product'),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name='update_product'),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('new/product/', views.NewProduct.as_view(), name='new_product'),
   
]

belleluxe/core/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User
 
# Create your models here.



class campaign(models.Model):
    lasteditor = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=30, default='generico')
    year=models.DateField(auto_now_add=True)
    def __str__(self):
        return self.name

class gender(models.Model):
    lasteditor = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=10, default='nonbinary')
    def __str__(self):
        return self.name

class category(models.Model):
    lasteditor = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=25, default='generic caegory')
    def __str__(self):
        return self.name

class payment(models.Model):
    name=models.CharField(max_length=10)
    reference=models.CharField(max_length=8)
    def __str__(self):
        return self.name

class customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name_first=models.CharField(max_length=35)
    last_name_pat=models.CharField(max_length=25)
    last_name_mat=models.CharField(max_length=25, blank=True)
    phone=models.CharField(max_length=15)
    cp=models.CharField(max_length=5)
    streat=models.CharField(max_length=25)
    number_home=models.CharField(max_length=3)
    def __str__(self):
        return self.user


class order(models.Model):
    payment=models.ForeignKey(payment, on_delete=models.CASCADE)
    customer=models.ForeignKey(customer, on_delete=models.CASCADE)
    date=models.DateField(auto_now_add=True)
    code_flow=models.CharField(max_length=10)
    subtotal=models.FloatField(default=0.0)
    IVA=models.FloatField(default=0.0)
    total=models.FloatField(default=0.0)
    def __str__(self):
        return self.payment

class product(models.Model):
    lasteditor = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=35)   
    campaign=models.ForeignKey(campaign, on_delete=models.CASCADE)
    gender=models.ForeignKey(gender, on_delete=models.CASCADE)
    category=models.ForeignKey(category, on_delete=models.CASCADE)
    description=models.CharField(max_length=256)
    size=models.CharField(max_length=4)
    price_uni=models.FloatField(default=0.0)
    status=models.BooleanField(default=False)
    stock=models.IntegerField(default=0)
    slug=models.SlugField(max_length=6)
    imagen1 = models.ImageField(upload_to='media/', null=True) 
    imagen2 = models.ImageField(upload_to='media/', null=True) 
    imagen3 = models.ImageField(upload_to='media/', null=True) 
    def __str__(self):
        return self.name

belleluxe/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *


class adm(generic.View):
    tamplate_name="core/admin.html"
    context={}
    def get(self, request, *args, **kwargs):
        return render(request, self.tamplate_name, self.context)
    



#Campaign--------------------------------------------------------------------------
class Campaign(generic.View):
   template_name="core/campaign/campaign.html"
   context={}
   def get(self,request):
       self.context= {
           "campaign": campaign.objects.all()
       }
       return render(request, self.template_name, self.context)
  
class DetailCampaign(generic.DetailView):
   template_name = "core/campaign/detail_campaign.html"
   model = campaign


class NewCampaign(generic.CreateView):
   template_name="core/campaign/NewCampaign.html"
   model = campaign
   form_class = NewCampaignform
   success_url = reverse_lazy("core:campaign")


class UpdateCampaign(generic.UpdateView):
   template_name="core/campaign/update_campaign.html"
   model = campaign
   form_class = UpdateCampaignForm
   success_url = reverse_lazy("core:campaign")


class DeleteCampaign(generic.DeleteView):
   template_name="core/campaign/delete_campaign.html"
   model = campaign
   success_url = reverse_lazy("core:campaign")


#Gender--------------------------------------------------------------------------
class list_gender(generic.View):
   template_name="core/gender/gender.html"
   context={}
   def get(self,request):
      genders = gender.objects.all()
      self.context = {
         "gender": genders
      }
      return render(request, self.template_name, self.context)

class NewGender(generic.CreateView):
   template_name="core/gender/New_gender.html"
   model = gender
   form_class = NewGenderForm
   success_url = reverse_lazy("core:gender")

class DetailGender(generic.DetailView):
   template_name = "core/gender/detail_gender.html"
   model = gender
   def get(self, request, pk, *args, **kwargs):
      genders = gender.objects.get(pk=pk)
      self.context = {
         "gender": genders
      }
      return render(request, self.template_name,self.context)

class UpdateGender(generic.UpdateView):
   template_name="core/gender/update_gender.html"
   model = gender
   form_class = UpdateGenderForm
   success_url = reverse_lazy("core:gender")

class DeleteGender(generic.DeleteView):
   template_name="core/gender/delete_gender.html"
   model = gender
   success_url = reverse_lazy("core:gender")

#Category--------------------------------------------------------------------------
class list_category(generic.View):
   template_name="core/category/category.html"
   context={}
   def get(self,request):
      categorys = category.objects.all()
      self.context = {
         "category": categorys
      }
      return render(request, self.template_name, self.context)

class NewCategory(generic.CreateView):
   template_name="core/category/New_category.html"
   model = category
   form_class = NewCategoryForm
   success_url = reverse_lazy("core:category")

class DetailCategory(generic.DetailView):
   template_name = "core/category/detail_category.html"
   model = category
   def get(self, request, pk, *args, **kwargs):
      categorys = category.objects.get(pk=pk)
      self.context = {
         "category": categorys
      }
      return render(request, self.template_name,self.context)

class UpdateCategory(generic.UpdateView):
   template_name="core/category/update_category.html"
   model = category
   form_class = UpdateCategoryForm
   success_url = reverse_lazy("core:category")

class DeleteCategory(generic.DeleteView):
   template_name="core/category/delete_category.html"
   model = category
   success_url = reverse_lazy("core:category")




#Payment--------------------------------------------------------------------------
class list_payment(generic.View):
   template_name="core/payment/payment.html"
   context={}
   def get(self,request):
      payments = payment.objects.all()
      self.context = {
         "payment": payments
      }
      return render(request, self.template_name, self.context)

class NewPayment(generic.CreateView):
   template_name="core/payment/New_payment.html"
   model = payment
   form_class = NewPaymentForm
   success_url = reverse_lazy("core:payment")

class DetailPayment(generic.DetailView):
   template_name = "core/payment/detail_payment.html"
   model = payment
   def get(self, request, pk, *args, **kwargs):
      payments = payment.objects.get(pk=pk)
      self.context = {
         "payment": payments
      }
      return render(request, self.template_name,self.context)

class UpdatePayment(generic.UpdateView):
   template_name="core/payment/update_payment.html"
   model = payment
   form_class = UpdatePaymentForm
   success_url = reverse_lazy("core:payment")

class DeletePayment(generic.DeleteView):
   template_name="core/payment/delete_payment.html"
   model = payment
   success_url = reverse_lazy("core:payment")


#Product--------------------------------------------------------------------------

class Product(generic.View):
   template_name = "core/product/product.html"
   context = {}
   def get(self, request, *args, **kwargs):
      products = product.objects.all()
      self.context = {
         "products": products
      }
      return render(request, self.template_name, self.context)

class NewProduct(generic.CreateView):
   template_name = "core/product/new_product.html"
   model = product
   form_class = NewProductForm
   success_url = reverse_lazy("core:product")
class RecoverProduct(generic.View):
   template_name = "core/product/recover_product.html"
   context = {}

   def get(self, request, pk, *args, **kwargs):
      self.context = {
         "product": product.objects.get(pk=pk)
      }
      return render(request, self.template_name,self.context)

class UpdateProduct(generic.UpdateView):
   template_name = "core/product/update_product.html"
   model = product
   form_class = UpdateProductForm
   success_url = reverse_lazy("core:product")

class DeleteProduct(generic.DeleteView):
   template_name = "core/product/delete_product.html"
   model = product
   success_url = reverse_lazy("core:product")


#Customer-----------------------------------------------------------------------
"""
class list_customer(generic.View):
   template_name="core/customer/customer.html"
   context={}
   def get(self,request):
       self.context= {
           "customer": customer.objects.all()
       }
       return render(request, self.template_name, self.context)
  
class Detailcustomer(generic.DetailView):
   template_name = "core/customer/detail_customer.html"
   model = customer


class Newcustomer(generic.CreateView):
   template_name="core/customer/NewCustomer.html"
   model = customer
   form_class = NewCustomerForm
   success_url = reverse_lazy("core:customer")


class Updatecustomer(generic.UpdateView):
   template_name="core/customer/update_customer.html"
   model = customer
   form_class = UpdateCustomerForm
   success_url = reverse_lazy("core:customer")


class Deletecustomer(generic.DeleteView):
   template_name="core/customer/delete_customer.html"
   model = customer
   success_url = reverse_lazy("core:customer")

#Order--------------------------------------------------------------------------

class list_order(generic.View):
   template_name="core/order/order.html"
   context={}
   def get(self,request):
       self.context= {
           "order": order.objects.all()
       }
       return render(request, self.template_name, self.context)
  
class Detailorder(generic.DetailView):
   template_name = "core/order/detail_order.html"
   model = order


class Neworder(generic.CreateView):
   template_name="core/order/NewOrder.html"
   model = order
   form_class = NewOrderForm
   success_url = reverse_lazy("core:order")


class Updateorder(generic.UpdateView):
   template_name="core/order/update_order.html"
   model = order
   form_class = UpdateOrderForm
   success_url = reverse_lazy("core:gender")


class Deleteorder(generic.DeleteView):
   template_name="core/order/delete_order.html"
   model = order
   success_url = reverse_lazy("core:order")
"""

belleluxe/templates/core/product/delete_product.html
{% extends 'base/admin.html' %}

{% block title %}
  DELETE PRODUCT VIEW
{% endblock title %}

{% block content %}
<br>
<br>
    <form action="" method="post">
        {% csrf_token %}
            <h4>Borrar Producto</h4>
            <p>¿Realmente deseas borrar este producto : {{ object.name }} ? </p>
            <button type="submit" class="btn btn-danger">Borrar Producto</button>
            <a href="{% url 'core:product' %}" class="btn btn-warning">Cancelar</a>
    </form>
{% endblock content %}  

belleluxe/templates/core/product/new_product.html
{% extends 'base/admin.html' %}

{% block title %}
  NEW PRODUCT VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control">Create Product</button>
        <br>
        <a href="{% url 'core:product' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

belleluxe/templates/core/product/product.html
{% extends 'base/admin.html' %}

{% block title %}
PRODUCT VIEW
{% endblock title %}

{% block content %}
<br> 
<center><h2>Productos</h2></center>
<br> 
<hr>
    <a href="{% url 'core:new_product' %}" class="btn btn-outline-success form-control">Create a New Product</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>Nombre del producto</th>
            <th>Campaña</th>
            <th>Descripción</th>
            <th>Status</th>
            <th>Cantidad</th>
            <th></th>
            <th>Acciones</th>
            <th></th>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.campaign }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.status }}</td>
                    <td>{{ product.stock }}</td>                    
                    <td><a href="{% url 'core:recover_product' product.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:update_product' product.id %}" class="btn btn-outline-warning"> Actualizar </a></td>
                    <td><a href="{% url 'core:delete_product' product.id %}" class="btn btn-outline-danger"> Borrar </a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    

{% endblock content %}

belleluxe/templates/core/product/recover_product.html
{% extends 'base/admin.html' %}

{% block title %}
  PRODUCT DETAIL VIEW
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Product Details</h2>
        <ul class="list-group">
          <li class="list-group-item"><strong>ID:</strong> {{ product.id }}</li>
          <li class="list-group-item"><strong>Name:</strong> {{ product.name }}</li>
          <li class="list-group-item"><strong>Description:</strong> {{ product.description }}</li>
          <li class="list-group-item"><strong>Campaign:</strong> {{ product.campaign }}</li>
          <li class="list-group-item"><strong>Gender:</strong> {{ product.gender }}</li>
          <li class="list-group-item"><strong>Category:</strong> {{ product.category }}</li>
          <li class="list-group-item"><strong>Size:</strong> {{ product.size }}</li>
          <li class="list-group-item"><strong>Price (Unit):</strong> {{ product.price_uni }}</li>
          <li class="list-group-item"><strong>Status:</strong> {{ product.status }}</li>
          <li class="list-group-item"><strong>Stock:</strong> {{ product.stock }}</li>
        </ul>
      </div>
        <div class="col-md-6">
          <img src="{{ product.imagen1.url }}" alt="{{ product.name }}" class="img-fluid">
        </div>
        
      </div>
  
        <br>
        <div class="row">
          <div class="column col-md-6"> 
            <img src="{{ product.imagen2.url }}" alt="{{ product.name }}" class="img-fluid">
          </div>
          <div class="column col-md-6"> 
            <img src="{{ product.imagen3.url }}" alt="{{ product.name }}" class="img-fluid">
          </div>
        </div> 
    <a href="{% url 'core:product' %}" class="btn btn-link">Volver</a>   
  </div>
{% endblock content %}

belleluxe/templates/core/product/update_product.html
{% extends 'base/admin.html' %}

{% block title %}
  UPDATE PRODUCT VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Update Product</button>
        <br>
        <a href="{% url 'core:product' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}